### ISSUE TITLE
README.md in English please!

### ISSUE THREAD

**Issue by Reamasa** [sonderlau/KuaiShouVideoDownload#1]
Can you make README.md in English? Thanks.

**Comment by sonderlau** [comment]
> Can you make README.md in English? Thanks.

Sure thing. I've been busy these days. So it will take like 1 or 2 days to make it.

BTW, this project has only been tested in Chinese version which may be different from the global version.

**Comment by Reamasa** [comment]
> > Can you make README.md in English? Thanks.
> 
> Sure thing. I've been busy these days. So it will take like 1 or 2 days to make it.
> 
> BTW, this project has only been tested in Chinese version which may be different from the global version.

Great to hear that! Thanks,

**Comment by sonderlau** [comment]
The english version of README in now online, you can check out [here](https://github.com/sonderlau/KuaiShouVideoDownload/blob/main/README_EN.md)

I'm sorry, due to some reasons(actually the Chinese Network has blocked github for no reasons), it took me about 3 days.

Considering this project is made for my assignments, so I'll remain the default README as Chinese version.

The codes are "Just work", not well enough to read, so just take it for fun :)

Please excuese for my poor English, and I cannot translate all the `Python` files and notations into English because of my limited time. For now I have a very important exam held on Christmas Day that I need to prepare for it with all my heart and soul.

If you have any problems, you can still open an issue, but I can't make sure to reply on time.

Please enjoy your Github tour, have a great day !

**Comment by Reamasa** [comment]
> 

Thank for you time. I wish you pass your important exam.
